---
version: "2.1"
services:
  static:
    image: nicholaswilde/static:latest
    container_name: static-default
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - data:/data
volumes:
  data:
